spring:
  application:
#    name: auth_service
    name: emp-mgmt-sys
  config:
    import: optional:configserver:http://localhost:8080
  cloud:
    config:
      fail-fast: true
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 5000

