spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oluemm/darum_config_repo
          default-label: main
server:
  port: 8080
  
#employee_sys:
#  service:
#    url: http://
